# docker-compose.yml

version: '3.9'

volumes:
  claude-memory:

networks:
  a0net: {}

services:
  memory:
    image: mcp/memory:latest
    container_name: memory
    # The mcp/memory image only communicates over STDIN. It does not
    # expose an HTTP API, so we keep stdin open and avoid port mapping.
    stdin_open: true
    volumes:
      - claude-memory:/app/dist
    networks:
      - a0net

  agent-zero:
    image: frdel/agent-zero-run:v0.8.5
    container_name: cranky_chaplygin
    volumes:
      - ./agent-zero:/a0
    ports:
      - "50080:80"
    depends_on:
      - memory
    networks:
      - a0net
