# docker-compose.yml

version: '3.9'

volumes:
  claude-memory:

networks:
  a0net: {}

services:
  memory:
    image: mcp/memory:latest
    container_name: memory
    command: ["memory", "--transport", "http", "--port", "4100"]
    ports:
      - "4100:4100"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4100/health"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 30s
    volumes:
      - claude-memory:/app/dist
    networks:
      - a0net

  agent-zero:
    image: frdel/agent-zero-run:v0.8.5
    container_name: cranky_chaplygin
    volumes:
      - ./agent-zero:/a0
    ports:
      - "50080:80"
    depends_on:
      memory:
        condition: service_healthy
    environment:
      MEMORY_URL: http://memory:4100
    networks:
      - a0net
