version: '3.9'

volumes:
  neo4j-data:
  neo4j-logs:

networks:
  a0net: {}

services:
  neo4j:
    image: neo4j:5.20
    container_name: neo4j
    environment:
      - NEO4J_AUTH=neo4j/password
    volumes:
      - neo4j-data:/data
      - neo4j-logs:/logs
    ports:
      - "7474:7474"
      - "7687:7687"
    healthcheck:
      test: ["CMD", "cypher-shell", "-u", "neo4j", "-p", "password", "RETURN 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - a0net

  memory:
    image: mcp/neo4j-memory:latest
    container_name: neo4j-memory
    stdin_open: true
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password
    depends_on:
      neo4j:
        condition: service_healthy
    networks:
      - a0net

  agent-zero:
    image: frdel/agent-zero-run:v0.8.5
    container_name: cranky_chaplygin
    volumes:
      - ./agent-zero:/a0
    depends_on:
      - memory
    ports:
      - "50080:80"
    networks:
      - a0net
